<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1146" started-at="2017-01-28T11:27:27Z" finished-at="2017-01-28T11:27:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1146" started-at="2017-01-28T11:27:27Z" finished-at="2017-01-28T11:27:28Z">
      <class name="com.test.demo.TestDemo">
        <test-method status="FAIL" signature="addTest()[pri:0, instance:com.test.demo.TestDemo@abd40ef]" name="addTest" duration-ms="884" started-at="2017-01-28T16:57:27Z" finished-at="2017-01-28T16:57:28Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[/hibernate.cfg.xml not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: /hibernate.cfg.xml not found
	at org.hibernate.internal.util.ConfigHelper.getResourceAsStream(ConfigHelper.java:173)
	at org.hibernate.cfg.Configuration.getConfigurationInputStream(Configuration.java:2005)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1986)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1966)
	at com.utility.UtilityClass.getSessionFactory(UtilityClass.java:10)
	at crudoperation.OperationOnProduct.addProduct(OperationOnProduct.java:23)
	at com.test.demo.TestDemo.addTest(TestDemo.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addTest -->
        <test-method status="FAIL" signature="removeTest()[pri:0, instance:com.test.demo.TestDemo@abd40ef]" name="removeTest" duration-ms="21" started-at="2017-01-28T16:57:28Z" finished-at="2017-01-28T16:57:28Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[/hibernate.cfg.xml not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: /hibernate.cfg.xml not found
	at org.hibernate.internal.util.ConfigHelper.getResourceAsStream(ConfigHelper.java:173)
	at org.hibernate.cfg.Configuration.getConfigurationInputStream(Configuration.java:2005)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1986)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1966)
	at com.utility.UtilityClass.getSessionFactory(UtilityClass.java:10)
	at crudoperation.OperationOnProduct.removeProduct(OperationOnProduct.java:50)
	at com.test.demo.TestDemo.removeTest(TestDemo.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removeTest -->
        <test-method status="FAIL" signature="retriveTest()[pri:0, instance:com.test.demo.TestDemo@abd40ef]" name="retriveTest" duration-ms="20" started-at="2017-01-28T16:57:28Z" finished-at="2017-01-28T16:57:28Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[/hibernate.cfg.xml not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: /hibernate.cfg.xml not found
	at org.hibernate.internal.util.ConfigHelper.getResourceAsStream(ConfigHelper.java:173)
	at org.hibernate.cfg.Configuration.getConfigurationInputStream(Configuration.java:2005)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1986)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1966)
	at com.utility.UtilityClass.getSessionFactory(UtilityClass.java:10)
	at crudoperation.OperationOnProduct.retriveProduct(OperationOnProduct.java:79)
	at com.test.demo.TestDemo.retriveTest(TestDemo.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retriveTest -->
        <test-method status="FAIL" signature="updateIdTest()[pri:0, instance:com.test.demo.TestDemo@abd40ef]" name="updateIdTest" duration-ms="21" started-at="2017-01-28T16:57:28Z" finished-at="2017-01-28T16:57:28Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[/hibernate.cfg.xml not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: /hibernate.cfg.xml not found
	at org.hibernate.internal.util.ConfigHelper.getResourceAsStream(ConfigHelper.java:173)
	at org.hibernate.cfg.Configuration.getConfigurationInputStream(Configuration.java:2005)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1986)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1966)
	at com.utility.UtilityClass.getSessionFactory(UtilityClass.java:10)
	at crudoperation.OperationOnProduct.updateProduct(OperationOnProduct.java:59)
	at com.test.demo.TestDemo.updateIdTest(TestDemo.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateIdTest -->
        <test-method status="FAIL" signature="updateStringTest()[pri:0, instance:com.test.demo.TestDemo@abd40ef]" name="updateStringTest" duration-ms="32" started-at="2017-01-28T16:57:28Z" finished-at="2017-01-28T16:57:28Z">
          <exception class="org.hibernate.HibernateException">
            <message>
              <![CDATA[/hibernate.cfg.xml not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.hibernate.HibernateException: /hibernate.cfg.xml not found
	at org.hibernate.internal.util.ConfigHelper.getResourceAsStream(ConfigHelper.java:173)
	at org.hibernate.cfg.Configuration.getConfigurationInputStream(Configuration.java:2005)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1986)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:1966)
	at com.utility.UtilityClass.getSessionFactory(UtilityClass.java:10)
	at crudoperation.OperationOnProduct.updateProduct(OperationOnProduct.java:69)
	at com.test.demo.TestDemo.updateStringTest(TestDemo.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.hibernate.HibernateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateStringTest -->
      </class> <!-- com.test.demo.TestDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
